### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sekunde** [skanti/ServerMeshViewer#6]
i install the code, and run but got following errors; and 
**Run ./server/run.sh to start the server.** should be **enter server folder and ./run.sh**

./run.sh: 1: ./run.sh: source: not found
base-url:

> MonitorNet@1.0.0 start /home/ji/ServerMeshViewer/server
> node --harmony ./index.js

Server listening at address http://:: in port: 8080
TypeError: path argument is required to res.sendFile
    at ServerResponse.sendFile (/home/ji/ServerMeshViewer/server/node_modules/express/lib/response.js:411:11)
    at /home/ji/ServerMeshViewer/server/index.js:62:6
    at Layer.handle [as handle_request] (/home/ji/ServerMeshViewer/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ji/ServerMeshViewer/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ji/ServerMeshViewer/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ji/ServerMeshViewer/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/ji/ServerMeshViewer/server/node_modules/express/lib/router/index.js:281:22
    at param (/home/ji/ServerMeshViewer/server/node_modules/express/lib/router/index.js:354:14)
    at param (/home/ji/ServerMeshViewer/server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/ji/ServerMeshViewer/server/node_modules/express/lib/router/index.js:410:3)

**Comment by skanti** [comment]
Use bash, then work-u
